name: Deploy Kubectl configuration

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        working-directory: ./deployments/kubectl
        run: |
          kubectl config set-credentials $(kubectl config current-context) --username=$(kubectl config current-context) --password=$(echo "${{ secrets.KUBECONFIG }}" | base64 -d | kubectl config get-credentials $(kubectl config current-context) -o json | jq -r .token)
          kubectl config set-context $(kubectl config current-context) --cluster=$(kubectl config current-context) --user=$(kubectl config current-context)
          kubectl config use-context $(kubectl config current-context)
          kubectl apply -f ./deployment.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
